import TourImg1 from '../../../asset/tour/t1.jpg';
import TourImg2 from '../../../asset/tour/t2.jpg';
import TourImg3 from '../../../asset/tour/t3.jpg';
import TourImg4 from '../../../asset/tour/t4.jpg';
import TourImg5 from '../../../asset/tour/t5.jpg';
import TourImg6 from '../../../asset/tour/t6.jpg';
import TourImg7 from '../../../asset/tour/t7.jpg';
import TourImg8 from '../../../asset/tour/t8.jpg';
import TourImg9 from '../../../asset/tour/t9.jpg';
import TourImg10 from '../../../asset/tour/t10.jpg';
import TourImg11 from '../../../asset/tour/t11.jpg';
import TourImg12 from '../../../asset/tour/t12.jpg';
import TourImg13 from '../../../asset/tour/t13.jpg';
import TourImg14 from '../../../asset/tour/t14.jpg';
import TourImg15 from '../../../asset/tour/t15.jpg';
import TourImg16 from '../../../asset/tour/t16.jpg';
import TourImg17 from '../../../asset/tour/t17.jpg';
import TourImg18 from '../../../asset/tour/t18.jpg';
import TourImg19 from '../../../asset/tour/t19.jpg';
import TourImg20 from '../../../asset/tour/t20.jpg';
import TourImg21 from '../../../asset/tour/t21.jpg';
import TourImg22 from '../../../asset/tour/t22.jpg';
import TourImg23 from '../../../asset/tour/t23.jpg';
import TourImg24 from '../../../asset/tour/t24.jpg';
import TourImg25 from '../../../asset/tour/t25.jpg';
import TourImg26 from '../../../asset/tour/t26.jpg';
import TourImg27 from '../../../asset/tour/t27.jpg';
import TourImg28 from '../../../asset/tour/t28.jpg';
import TourImg29 from '../../../asset/tour/t29.jpg';
import TourImg30 from '../../../asset/tour/t30.jpg';
import TourImg31 from '../../../asset/tour/t31.jpg';
import TourImg32 from '../../../asset/tour/t32.jpg';
import TourImg33 from '../../../asset/tour/t33.jpg';

export const TourData = (tourpackages) => {
  const data = [
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg1,
      text: 'Australia',
      textHeading: '08D Precious East Coast Aussie',
      cNamePrice: 'price',
      text2: 'Start from',
      category: 'popularity',
      currency: 'Rp',
      price: '19,800,000',
      descTourHover: 'Pengalaman liburan tak terlupakan akan Anda dapatkan dengan mengambil paket ini. Anda akan kami ajak melakukan berbagai pengalaman seru, mulai dari eksplore kota Sydney sampai puas, melihat koala menggemaskan di Featherdale Wildlife Park, mencicipi wine di Audrey Wilkinson Winery, melihat paus dari atas kapal cruise, mencoba naik kereta luncur berpasir di Tangalooma, hingga menyaksikan indahnya pemandangan malam kota Melbourne dari atas Eureka Melbourne Skydeck. Ayo, reservasi paket ini sekarang untuk keberangkatan hingga 25 Juni 2022.',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg2,
      text: 'Australia',
      textHeading: '6D Mono Sydney Experience',
      cNamePrice: 'price',
      category: 'popularity',
      text2: 'Start from',
      currency: 'Rp',
      price: '19,800,000',
      descTourHover: 'Berpetualang di Sydney menjadi mungkin jika Anda mengambil paket ini. Anda akan kami ajak city tour di kota Sydney seharian penuh dengan mengunjungi tempat-tempat wisata yang menarik, sebut saja seperti Sydney Opera House yang merupakan bangunan khas negara Australia, Captain Cook Cruise, dan Sydney Brigde. Selain itu, Anda juga akan mencoba pengalam seru naik unta di Port Stephens, menikmati anggur di Audrey Wilkinson Winery, hingga melihat koala di Featherdale Wildlife Park. Jadi, tunggu apa lagi? Ayo reservasi paket ini sekarang untuk perjalanan hingga Juni 2022.',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg3,
      text: 'Australia',
      textHeading: '5 Days Dazzle Vivid Sydney + Port Stephens',
      cNamePrice: 'price',
      category: 'popularity',
      text2: 'Start from',
      currency: 'Rp',
      price: '19,800,000',
      descTourHover: 'Bingung mau liburan kemana tahun ini? Untuk rekomendasi, kamu bisa ambil paket liburan lima hari ke Sydney dan Port Stephens, Australia. Anda akan merasakan liburan mengasyikkan dengan mengunjungi banyak spot terkenal di Sydney. Lalu, mencoba pengalaman seru naik Vivid Sydney Cruise yang mewah. Tak terlupakan, Anda juga akan merasakan naik unta, melhat lumba-lumba, dan naik 4WD Sandboarding di Port Stephens. Reservasi paket ini sekarang untuk perjalanan hingga Juni 2022.',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg4,
      text: 'Family Holidays',
      textHeading: '5D4N Madrid Free & Easy',
      cNamePrice: 'price',
      category: 'popularity',
      text2: 'Start from',
      currency: 'Rp',
      price: '21,953,000',
      descTourHover: 'Ayo, rasakan kembali liburan ke Madrid, Spanyol. Anda akan diberikan waktu lima hari untuk menjelajahi indahknya Kota Madrid secara bebas. Anda bisa mengunjungi tempat-tempat liburan di Madrid sesuka Anda. Kapan lagi bisa merasakan liburan semenyenangkan ini? Reservasi paket ini sekarang untuk keberangkatan hingga Desember 2022.',
      details: 'More Details',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg5,
      text: 'Familiy Holiday',
      textHeading: '3D Package Banda Aceh',
      cNamePrice: 'price',
      category: 'popularity',
      text2: 'Start from',
      currency: 'Rp',
      price: '2,225,000',
      descTourHover: 'Sebagai kota yang menyimpan banyak sejarah, Banda Aceh patut Anda kunjungi di liburan kali ini. Anda akan diajak berziarah ke Tugu Tsunami di Siron, tugu yang menyimpan memori tak terlupakan saat Aceh dilanda Tsunami. Lalu, Anda akan diajak jalan-jalan mengunjungi objek wisata terkenal di Banda Aceh sebelum menyebrang ke Sabang. Di Sabang, Anda akan diajak ke Tugu Kilometer Nol Indonesia, bersantai di Pantai Iboih, snorkeling di Taman Bawah Laut Rubiah, hingga menikmati sunset di Sabang Fair. Reservasi paket ini sekarang untuk keberangkatan hingga akhir 2022.',
      details: 'More Details',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg6,
      text: 'Family Holidays',
      textHeading: '7D Cheer Up Korea Jeju (22 December 2022)',
      cNamePrice: 'price',
      category: 'popularity',
      text2: 'Start from',
      currency: 'Rp',
      price: '21,800,000',
      descTourHover: 'Rencanakan liburan Natal Anda dengan berwisata ke Korea Selatan. Anda akan diajak tak hanya menelusuri Kota Seoul yang modern, tetapi juga jalan-jalan ke Pulau Jeju-nya yang cantik. Ayo, segera ambil paket wisata ini dan rasakan pengalaman tak terlupakan menikmati sunset di Jeju, melihat indahnya Seongup Folk Village, jalan-jalan di Gwongsemsong Fortress, berfoto dengan Hanbok di Gyeongbok Palace, hingga berbelanja di Dongdaemun Market. Reservasi paket ini sekarang untuk keberangkatan tanggal 22 Desember 2022.',
      details: '1 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg7,
      text: 'Family Holidays',
      textHeading: '7D Cheer Up Korea Jeju (29 December 2022)',
      cNamePrice: 'price',
      category: 'popularity',
      text2: 'Start from',
      currency: 'Rp',
      price: '23,800,000',
      descTourHover: 'Habiskan libur Natal dan Tahun Baru Anda dengan mengunjungi Kota Seoul dan Pulau Jeju di Korea Selatan. Pulau Jeju yang indah bisa anda eksplore bersama kami. Nikmati indahnya pemandangan matahari terbit di Sunrise Peak, berfoto di Nami Island yang cantik, bermain sampai puas di Everland Theme Park, mengunjungi objek wisata terkenal N-Seoul Tower, hingga menelusuri jalan Gangnam Street yang terkenal. Reservasi paket ini sekarang untuk keberangkatan tanggal 29 Desember 2022.',
      details: '1 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg8,
      text: 'Family Holidays',
      textHeading: '5D4N London Free & Easy',
      cNamePrice: 'price',
      category: 'popularity',
      text2: 'Start from',
      currency: 'Rp',
      price: '17,533,000',
      descTourHover: 'Kota London memiliki pesonanya yang mampu menyihir siapa pun untuk datang kembali. Sebagai kota modern yang indah, London mengajak Anda untuk liburan kembali ke sana tahun ini. Ambil paket ini dan Anda akan menikmati liburan selama lima hari di London secara bebas. Anda dapat mengeksplor, keliling-keliling, jalan-jalan, dan menikmati London secara puas selama seharian penuh. Reservasi paket ini sekarang untuk keberangkatan hingga Desember 2022.',
      details: 'More Details',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg9,
      text: 'Family Holidays',
      textHeading: '5Days Pop Up Korea By KE',
      cNamePrice: 'price',
      category: 'popularity',
      text2: 'Start from',
      currency: 'Rp',
      price: '17,800,000',
      descTourHover: 'Habiskan musim semi kamu dengan berlibur di Korea Selatan. Ayo, jangan lewarkan kesempatan untuk melihat indahnya bunga bermekaran di Nami Island. Lalu, potret momen liburan seru kamu di Soyanggang Skywalk, Gwanghwamun Square, dan di Gyeongbok Palace. Tak lupa, nikmati serunya jalan-jalan di Gwongsemsong Fortress dan Myeongdong yang terkenal. Ayo, reservasi paket ini sekarang untuk keberangkatan hingga 5 April 2023.',
      details: '1 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg10,
      text: 'Family Holidays',
      textHeading: '7Days Cheers Korea By KE',
      cNamePrice: 'price',
      category: 'popularity',
      text2: 'Start from',
      currency: 'Rp',
      price: '21,800,000',
      descTourHover: 'Seoul dan Jeju adalah dua kota di Korea Selatan yang memancarkan pesona berbeda. Jika seoul tampil sebagai kota modern, maka Jeju hadir dengan keindahan alamnya yang masih alami. Ayo, rasakan sensasi liburan di dua kota tersebut selama musim semi di Korea. Anda akan diajak ke Teddy Bear Museum di Pulau Jeju, menikmati matahari terbit di Sunrise Peak, melihat bangunan rumah tradisional di Seongup Folk Village, berfoto dengan latar belakang bunga yang bermekaran di Nami Island dan Gyeongbok Palace, hingga berbelanja di Dongdaemun Market yang terkenal. Reservasi paket ini sekarang untuk keberangkatan hingga 5 April 2023.',
      details: '2 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg11,
      text: 'Family Holidays',
      textHeading: '10D Winter Turkey By QR',
      cNamePrice: 'price',
      category: 'popularity',
      text2: 'Start from',
      currency: 'Rp',
      price: '21,800,000',
      descTourHover: 'Yuk, habiskan momen liburan akhir tahun dan awal tahun di Turki. Menawarkan pemandangan musim dingin yang indah, Turki cocok menjadi destinasi liburan Anda kali ini. Anda akan kami ajak melihat Hagia Sophia yang megah, mengunjungi Blue Mosque, jalan-jalan ke Hierapolis, eksplore kota Cappadocia yang indah dengan balon udaranya, menikmati pemandangan laut Istanbul yang indah dari atas Bosphorus Cruise, hingga berbelanja oleh-oleh khas Turki di Grand Bazaar. Reservasi sekarang untuk keberangkatan tanggal 26 Desember 2022.',
      details: '2 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg12,
      text: 'Family Holidays',
      textHeading: '4D Ho Chi Minh - Cu Chi - Mekong Delta',
      cNamePrice: 'price',
      category: 'popularity',
      text2: 'Start from',
      currency: 'Rp',
      price: '6,800,000',
      descTourHover: 'Tak jauh dari Indonesia, Vietnam bisa menjadi pilihan destinasi liburan Anda bersama keluarga di tahun ini. Vietnam akan memberikan Anda pengalaman liburan yang tak terlupakan. Anda akan diajak berbelanja di Ben Thanh Market, mengunjungi Cu Chi Tunnels, jalan-jalan di Saigon, hingga bersantai di beberapa pulau, seperti Dagon Island, Unicorn Island, Phoenix Island, dan Turtle Island. Ayo, reservasi paket ini sekarang untuk keberangkatan hingga 22 Desember 2022.',
      details: 'More Details',
    }
  ];
  const otherData = [
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg13,
      text: 'Family Holidays',
      textHeading: '7D Explore Dubai',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '17,800,000',
      descTourHover: 'Yuk, eksplore Dubai menyaksikan keindahannya yang menakjubkan selama tujuh hari! Anda berkesempatan untuk mengunjungi tempat-tempat penuh sejarah, seperti ke Masjid King Faisal, Ajman Museum, UAQ Fort, Dhayah Fort, dan Al Bidyah Mosque. Anda juga akan mengunjungi ikon-ikon terkenal di Dubai seperti Burj Al Arab, Atlantis the Palm, Dubai Marina, dan Burj Khalifa. Begitu juga ketika di Abu Dhabi, kami akan membawa Anda ke destinasi terkenal, salah satunya Sheikh Zayed Grand Mosque, yang merupakan masjid terbesar di negara Arab. Segera dapatkan paketnya dan bersiaplah berlibur ke negara timur tengah bersama kami.',
      details: 'More Details',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg14,
      text: 'Family Holidays',
      textHeading: '7Days Kawaii Japan + Theme Park',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '32,800,000',
      descTourHover: 'Liburan ke Jepang selalu menyenangkan. Banyak objek wisata, kuliner, hingga tempat bermain seru di Jepang. Ayo, ambil paket liburan ke Jepang sekarang dan rasakan momen liburan tak terlupakan. Anda akan diajak mengelilingi Nakamise Street, berswafoto di Tokyo Skytree, berbelanja di Ginza, bermain di Disneysea dan Universal Studio Japan, menikmati pemandangan Gunung Fuji yang indah, mengunjungi objek wisata terkenal Fushimi Inari Shrine, hingga mengeksplore Shinsaibashi Area. Reservasi paket liburan ke Jepang untuk keberangkatan tanggal 2 April 2023.',
      details: '4 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg15,
      text: 'Family Holidays',
      textHeading: '5D Bangkok Pattaya By Thai Lion',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '8,800,000',
      descTourHover: 'Paket libur ke Bangkok dan Pattaya menanti Anda hingga awal tahun depan. Ayo, ajak keluarga dan orang terkasih mengeksplore banyak tempat wisata nan bersejarah di Bangkok dan Pattaya. Kami akan mengajak Anda berswafoto di Wat Arun yang terkenal, melihat Four Face Buddha, jalan-jalan di Pattaya, mengunjungi Pattaya Floating Market, hingga berbelanja sampai puas di MBK Mall dan Platinum. Ayo, reservasi paket ini sekarang untuk keberangkatan hingga Maret 2023.',
      details: 'More Details',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg16,
      text: 'Family Holidays',
      textHeading: '5D Melbourne Open Trip',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '5,800,000',
      descTourHover: 'Ingin liburan murah ke Melbourne? Kami punya paket wisatanya untuk Anda. Melbourne Open Trip selama 5 hari menawarkan liburan murah buat Anda yang ingin mengeksplore Kota Melbourne. Anda memiliki waktu bebas jalan-jalan di Melbourne dan Gold Coast. Anda juga berkesempatan mengikuti Trip Philip Island dengan mengunjungi Brighton Beach, Moonlit Sanctuary, Nobbies Seal Rock, dan Penguin Parade. Reservasi paket ini sekarang untuk perjalanan hingga Maret 2023.',
      details: 'More Details',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg17,
      text: 'Family Holidays',
      textHeading: '5D Pop Up Korea By KE',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '16,800,000',
      descTourHover: 'Belum tahu mau liburan ke mana tahun depan? Tak usah bingung, kami rekomendasikan Korea Selatan sebagai destinasi liburan kamu selanjutnya. Ada banyak tempat wisata seru, pemandangan indah, hingga kuliner menggiurkan di Seoul. Rasakan pengalaman liburan menyenangkan dengan jalan-jalan di Gwanghwamun Square, berfoto dengan latar daun-daun indah di Nami Island, bermain di Everland, berswafoto dengan baju hanbok di Gyeongbok Palace, hingga mengeksplore Myeongdong yang terkenal. Reservasi paket ini sekarang untuk keberangkatan hingga 21 Juli 2023.',
      details: '6 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg18,
      text: 'Family Holidays',
      textHeading: '7D Cheers Korea Jeju By SQ',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '19,800,000',
      descTourHover: 'Tersedia paket liburan seru ke dua tempat sekaligus, yakni Seoul dan Jeju untuk Anda. Ayo, ajak sahabat, keluarga, atau orang terkasih Anda liburan ke Korea Selatan tahun depan. Kami akan mengajak Anda jalan-jalan di Jeju, menikmati matahari terbit di Sunrise Peak, melihat rumah tradisional di Pulau Jeju, berswafoto dengan latar belakang dedaunan cantik di Nami Island, berlibur ke Everland, hingga melihat pemandangan indah di Gwongsemsong Fortress. Reservasi paket ini sekarang untuk keberangkatan hingga 5 April 2023.',
      details: '1 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg19,
      text: 'Family Holidays',
      textHeading: '5D Gold Coast Open Trip',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '5,800,000',
      descTourHover: 'Ingin mengeksplore Kota Gold Coast secara bebas? Nah, ini tersedia paketnya buat Anda. Dengan mengambil paket Open Trip, Anda berkesempatan mengeksplore Kota Gold Coast secara bebas. Anda juga berkesempatan diajak bermain di Movie World dan diajak liburan ke Paradise Country Farm. Paket ini pun juga sudah termasuk penginapan dan transportasi. Tunggu apa lagi? Langsung aja reservasi sekarang untuk perjalanan hingga Maret 2023.',
      details: 'More Details',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg20,
      text: 'Family Holidays',
      textHeading: '8D Yokosa Japan + Theme Park',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '36,800,000',
      descTourHover: 'Jepang menjadi negara destinasi liburan yang tak pernah salah. Dengan segala pesona yang dimilikinya, ayo ciptakan momen liburan seru ke Tokyo, Kyoto, dan Osaka. Anda akan diajak jalan-jalan di Nakamise Street, bermain di Disneysea Tokyo dan Universal Studio Japan, mengagumi keindahan Gunung Fuji, berswafoto di Fushimi Inari yang terkenal, menelusuri Shinsaibashi Area, mengunjungi Osaka Castle, hingga berbelanja di Rinku Premium Outlet. Reservasi paket liburan ke Jepang untuk keberangkatan tanggal 11 Februari 2023.',
      details: '1 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg21,
      text: 'Family Holidays',
      textHeading: '7Days Cheers Korea Jeju By SQ',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '18,800,000',
      descTourHover: 'Tersedia paket liburan seru ke dua tempat sekaligus, yakni Seoul dan Jeju untuk Anda. Ayo, ajak sahabat, keluarga, atau orang terkasih Anda liburan ke Korea Selatan tahun depan. Kami akan mengajak Anda jalan-jalan di Jeju, menikmati matahari terbit di Sunrise Peak, melihat rumah tradisional di Pulau Jeju, berswafoto dengan latar belakang dedaunan cantik di Nami Island, berlibur ke Everland, hingga melihat pemandangan indah di Gwongsemsong Fortress. Reservasi paket ini sekarang untuk keberangkatan hingga 21 Juli 2023.',
      details: '6 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg22,
      text: 'Family Holidays',
      textHeading: '5D Perth Open Trip',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '7,800,000',
      descTourHover: 'Jelajahi Perth selama lima hari hari sesuka Anda! Dengan mengikuti paket ini, Anda akan kami ajak trip ke Kota Perth, Kota Frementle yang kota pelabuhan di Australia Barat yang merupakan bagian dari wilayah metropolitan Perth selama satu hari, lalu mengeksplore Kota Gold Coast, hingga mencoba pengalaman menaiki Sand Boarding 4WD. Reservasi paket Open Trip ini untuk menikmati Perth dengan jadwal keberangkatan hingga Maret 2023.',
      details: 'More Details',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg23,
      text: 'Family Holidays',
      textHeading: '8D Yokosa Japan + Theme Park by SQ',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '32,800,000',
      descTourHover: 'Dengan segala pesona yang dimiliki Jepang, ayo ciptakan momen liburan seru ke Tokyo dan Osaka. Anda akan diajak jalan-jalan. Anda akan diajak ke Osaka Castle, bermain sampai puas di Universal Studio dan Disneysea, berswafoto dengan latar belakang MT Fuji, menikmati indahnya Lake Kawaguchi dan Hakone Lake, hingga jalan-jalan di Shibuya dan Ginza. Reservasi paket liburan ke Jepang untuk keberangkatan hingga 27 Juli 2023.',
      details: '6 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg24,
      text: 'Family Holidays',
      textHeading: '13D Have Fun West Europe',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '30,800,000',
      descTourHover: 'Mau liburan ke Eropa? Italia, Swiss, Jerman, Belanda, Belgia, hingga Paris sudah menunggu Anda! Ayo, ambil paket ini dan rasakan liburan menyenangkan ke 6 negara dan 10 kota di Eropa. Anda akan diajak mengelilingi kota Roma, melihat bangunan-bangunan bersejarah megah yang terkenal di Eropa, berfoto di Leaning Tower of Pisa, menelusuri kota Venice yang cantik, naik ke MT Titlis, hingga jalan-jalan seharian secara bebas di Frankfurt. Reservasi paket ini sekarang untuk perjalanan tanggal 28 Februari 2023.',
      details: '1 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg25,
      text: 'Family Holidays',
      textHeading: '5D Sydney Open Trip',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '6,800,000',
      descTourHover: 'Ingin mengeksplore Sydney secara bebas? Nah, ini tersedia paket Open Trip buat Anda. Dengan mengambil paket ini, Anda akan diajak trip ke Blue Mountain termasuk Featherdale Wildlife dan Scenic World, lalu mengeksplore Kota Gold Coast, kemudian mengikuti Sydney Lunch Buffet Cruise, dan diakhiri dengan mengunjungi Sydney Aquarium. Tunggu apa lagi? Langsung aja reservasi sekarang untuk perjalanan hingga Maret 2023.',
      details: 'More Details',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg26,
      text: 'Family Holidays',
      textHeading: '13D Have Fun West Europe By EK',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '31,800,000',
      descTourHover: 'Ayo, habiskan liburan awal tahun Anda bersama kami ke West Europe selama tiga belas Hari. Ambil paket ini dan rasakan liburan menyenangkan ke 5 negara dan 9 kota di Eropa. Anda dan keluarga akan diajak mengelilingi kota Roma, melihat bangunan-bangunan bersejarah megah yang terkenal di Eropa, berfoto di Leaning Tower of Pisa, menelusuri kota Venice yang cantik, naik ke MT Titlis, hingga jalan-jalan seharian secara bebas di Paris. Reservasi paket ini sekarang untuk perjalanan tanggal 28 Maret 2022.',
      details: '1 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg27,
      text: 'Family Holidays',
      textHeading: '13Days Have Fun West Europe',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '30,800,000',
      descTourHover: 'Ciptakan momen liburan menyenangkan dengan mengunjungi Eropa. Yuk, segera ambil paket ini dan Anda akan kami ajak ke Kota Roma, berswafoto di Leaning Tower of Pisa, berbelanja ke Foxtown Outlet Lugano di Zurich, Melihat indahnya MT Titlis, menelusuri Kota Amsterdam, hingga jalan-jalan di Belgia hingga Paris. Reservasi paket ini sekarang untuk perjalanan tanggal 20 Maret 2023.',
      details: '1 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg28,
      text: 'Family Holidays',
      textHeading: '3D Seoul 2Can Go',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '3,850,000',
      descTourHover: 'Berlibur ke Seoul lebih bahagia dengan harga yang murah meriah. Yuk, ambil paket ini dan ciptakan momen liburan yang tak terlupakan. Selama di Seoul 3 hari, Anda akan diajak berwisata ke Gyeongbok Palace yang terkenal menggunakan Hanbok, mengunjungi National Folklore Musem, berfoto di Bukchon Hanok Village, hingga berbelanja di Dongdaemun serta beberapa store ternama lainnya di Korea. Segera reservasi paket liburan murah ini untuk keberangkatan hingga Juni 2023.',
      details: 'More Details',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg29,
      text: 'Family Holidays',
      textHeading: '13D Holyland Petra + Cairo',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '42,800,000',
      descTourHover: 'Mari, dekatkan diri kepada Tuhan dengan melakukan perjalanan Rohani ke Holyland. Selama melakukan perjalanan rohani, Anda akan mengunjungi tempat-tempat penting bagi umat Katholik maupun Kristen Protestan seperti mendaki ke Gunung Sinai tempat Musa menerima 10 perintah Tuhan, melihat Kolam Bethesda yang merupakan tempat Yesus menyembuhkan orang lumpuh, mengunjungi Gereja ST Peter di Galicantu di mana Petrus menyangkal Yesus 3 kali, pergi ke Bukit Sion untuk mengunjungi Ruang Perjamuan Terakhir dan melihat makam Raja Daud, mengunjungi Gunung Nebo tempat Nabi Musa melihat Tanah Kanaan sebelum wafat, dan ke tempat-tempat rohani lainnya. Ayo, reservasi paket Holyland ini untuk keberangkatan tanggal 12 Maret 2023.',
      details: '1 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg30,
      text: 'Family Holidays',
      textHeading: '10Days Amazing Turkey by EK',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '17,800,000',
      descTourHover: 'Setelah liburan tertunda selama beberapa waktu, ayo, kali ini rayakan liburan seru ke Turki. Bersama keluarga atau orang terkasih, Anda akan diajak mengelilingi enam kota di Turki selama 10 hari. Anda akan diajak melakukan hal-hal mengasyikan, mulai dari mengunjungi Grand Mosque, melihat keajaiban Ephesus Ancient City, melihat keindahan Cotton Castle, naik balon udara di Cappadocia, masuk ke Hagia Sophia, hingga menyaksikan indahnya Istanbul dari atas Bosphorus Cruise. Ayo, reservasi sekarang untuk keberangkatan hingga 28 Juli 2023.',
      details: '5 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg31,
      text: 'Family Holidays',
      textHeading: '9D Precious East Coast Aussie',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '36,800,000',
      descTourHover: 'Rencanakan liburan Anda bersama keluarga dengan mengunjungi Melbourne, Gold Coast, dan Sydney. Beragam objek wisata seru dan menyenangkan telah menanti untuk Anda kunjungi. Anda akan diajak melihat Shrine of Remembrance, lalu berswafoto di Melbourne Street Art, menikmati kuliner di Queen Victoria Market, bermain sand toboganing di Tangalooma, berbelanja di Harbour Town Outlet, hingga menikmati anggur di Audrey Wilkinson Winery. Ayo, reservasi paket ini untuk keberangkatan tanggal 17 April 2023.',
      details: '1 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg32,
      text: 'Family Holidays',
      textHeading: '12D Fabulous East Europe by QR',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '32,800,000',
      descTourHover: 'Ayo, ajak orang terkasih Anda berlibur ke Eropa. Austria, Ceko, Polandia, Slovakia, dan Hongaria bakal menjadi destinasi berlibur yang seru di tahun 2023 ini. Jika mengambil paket ini, Anda akan diajak berfoto di ikon Kota Vienna, seperti Hofburg Palace, Schonbrunn Palace, dan Vienna Cathedral. Lalu, jalan-jalan di Prague, mengunjungi Bratislava Castle, hingga ke Mozart House. Ayo, reservasi paket ini sekarang untuk perjalanan hingga 18 Juli 2023.',
      details: '6 Departure Dates',
    },
    {
      containerData: 'container-data',
      cNameContainer: 'wrapp-img-tour',
      cName: 'desc-tour',
      img1: TourImg33,
      text: 'Family Holidays',
      textHeading: '13D Spain Portugal Maroco by EK',
      cNamePrice: 'price',
      text2: 'Start from',
      currency: 'Rp',
      price: '28,800,000',
      descTourHover: 'Ajak keluarga Anda liburan spektakuler ke Maroko, Spanyol, dan Portugal. Anda akan dibawa liburan seru-seruan ke berbagai kota di 3 negara tersebut, mulai dari mengunjungi Hasan II Mosque, jalan-jalan ke Cape Spartel, masuk ke Alhambra Castle, eksplore Kota Madrid, hingga jalan-jalan sampai puas di Barcelona. Ayo, reservasi paket tur ini sekarang untuk keberangkatan hingga 27 Juli 2023.',
      details: '6 Departure Dates',
    },
  ];
  if (tourpackages) {
    return [...otherData, ...data]
  }
  return data
}

export default TourData